apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nimiq-simple-faucet.fullname" . }}
  labels:
    {{- include "nimiq-simple-faucet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "nimiq-simple-faucet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nimiq-simple-faucet.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "nimiq-simple-faucet.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: faucet
          image: "{{ .Values.image.repository }}:{{ include "nimiq-simple-faucet.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "nimiq-simple-faucet.fullname" . }}
            {{- if or .Values.secrets.external.enabled .Values.secrets.values }}
            - secretRef:
                name: {{ include "nimiq-simple-faucet.secretName" . }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- if eq (include "nimiq-simple-faucet.sqliteMode" .) "true" }}
            - name: data
              mountPath: /data
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- if eq (include "nimiq-simple-faucet.sqliteMode" .) "true" }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "nimiq-simple-faucet.fullname" . }}-data
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
