{{- if .Values.secrets.external.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nimiq-simple-faucet.secretName" . }}
  labels:
    {{- include "nimiq-simple-faucet.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStoreRef.name | quote }}
    kind: {{ .Values.secrets.external.secretStoreRef.kind | default "ClusterSecretStore" | quote }}
  target:
    name: {{ include "nimiq-simple-faucet.secretName" . }}
    creationPolicy: Owner
  data:
    {{- range $envName, $ref := .Values.secrets.external.data }}
    - secretKey: {{ $envName | quote }}
      remoteRef:
        key: {{ $ref.remoteRef.key | quote }}
        {{- if $ref.remoteRef.property }}
        property: {{ $ref.remoteRef.property | quote }}
        {{- end }}
        {{- if $ref.remoteRef.version }}
        version: {{ $ref.remoteRef.version | quote }}
        {{- end }}
    {{- end }}
{{- end }}
