# Funding links displayed on the GitHub "Sponsor" button.
# Uncomment the relevant lines when sponsorship is enabled.

# github: PanoramicRum
# open_collective: nimiq-simple-faucet
custom:
  - https://nimiq.com
