/**
 * Land-mask lookup for the Nimiq PoW theme's hex-dot world map.
 *
 * Backed by a precomputed boolean bitmap derived from Natural Earth
 * 110m Admin-0 Countries (CC0, public domain). The bitmap lives in
 * `landmask-data.ts` and is regenerated by `/tmp/tessellate.js` when
 * the source data is refreshed. Antarctica is excluded from the
 * source set so the rendered map doesn't carry a horizontal band at
 * the bottom edge.
 *
 * Lookup is O(1) — a direct index into a fixed-size string. The
 * `WorldMap.vue` renderer iterates its hex grid once and calls this
 * for each cell.
 */

import {
  LAND_BITMAP,
  LAND_BITMAP_H,
  LAND_BITMAP_LAT_MAX,
  LAND_BITMAP_W,
} from './landmask-data';

export function isLand(lng: number, lat: number): boolean {
  // Map (lng, lat) to bitmap (col, row).
  // Bitmap is 1° per cell; lng spans -180..+180, lat spans
  // (LAT_MAX - LAND_BITMAP_H) .. LAT_MAX.
  const col = Math.floor(lng + 180);
  const row = Math.floor(LAND_BITMAP_LAT_MAX - lat);
  if (col < 0 || col >= LAND_BITMAP_W) return false;
  if (row < 0 || row >= LAND_BITMAP_H) return false;
  return LAND_BITMAP.charCodeAt(row * LAND_BITMAP_W + col) === 49; // '1'
}
